{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "mediterranean-century",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    import google.colab  # noqa: F401\n",
    "except ImportError:\n",
    "    pass\n",
    "else:\n",
    "    !wget \"https://fem-on-colab.github.io/releases/occ-install.sh\" -O \"/tmp/occ-install.sh\" && bash \"/tmp/occ-install.sh\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "proud-proceeding",
   "metadata": {},
   "outputs": [],
   "source": [
    "output = \"\"\n",
    "error = \"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "75ea8271",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%file tutorial_bottle.cpp\n",
    "\n",
    "// https://github.com/Open-Cascade-SAS/OCCT/blob/master/samples/OCCTOverview/code/MakeBottle.h\n",
    "// https://github.com/Open-Cascade-SAS/OCCT/blob/master/samples/OCCTOverview/code/MakeBottle.cxx\n",
    "\n",
    "#include <Standard_Macro.hxx>\n",
    "#include <TopoDS_Shape.hxx>\n",
    "\n",
    "#include <BRep_Tool.hxx>\n",
    "\n",
    "#include <BRepAlgoAPI_Fuse.hxx>\n",
    "\n",
    "#include <BRepBuilderAPI_MakeEdge.hxx>\n",
    "#include <BRepBuilderAPI_MakeFace.hxx>\n",
    "#include <BRepBuilderAPI_MakeWire.hxx>\n",
    "#include <BRepBuilderAPI_Transform.hxx>\n",
    "\n",
    "#include <BRepFilletAPI_MakeFillet.hxx>\n",
    "\n",
    "#include <BRepLib.hxx>\n",
    "\n",
    "#include <BRepOffsetAPI_MakeThickSolid.hxx>\n",
    "#include <BRepOffsetAPI_ThruSections.hxx>\n",
    "\n",
    "#include <BRepPrimAPI_MakeCylinder.hxx>\n",
    "#include <BRepPrimAPI_MakePrism.hxx>\n",
    "\n",
    "#include <GC_MakeArcOfCircle.hxx>\n",
    "#include <GC_MakeSegment.hxx>\n",
    "\n",
    "#include <GCE2d_MakeSegment.hxx>\n",
    "\n",
    "#include <gp.hxx>\n",
    "#include <gp_Ax1.hxx>\n",
    "#include <gp_Ax2.hxx>\n",
    "#include <gp_Ax2d.hxx>\n",
    "#include <gp_Dir.hxx>\n",
    "#include <gp_Dir2d.hxx>\n",
    "#include <gp_Pnt.hxx>\n",
    "#include <gp_Pnt2d.hxx>\n",
    "#include <gp_Trsf.hxx>\n",
    "#include <gp_Vec.hxx>\n",
    "\n",
    "#include <Geom_CylindricalSurface.hxx>\n",
    "#include <Geom_Plane.hxx>\n",
    "#include <Geom_Surface.hxx>\n",
    "#include <Geom_TrimmedCurve.hxx>\n",
    "\n",
    "#include <Geom2d_Ellipse.hxx>\n",
    "#include <Geom2d_TrimmedCurve.hxx>\n",
    "\n",
    "#include <TopExp_Explorer.hxx>\n",
    "\n",
    "#include <TopoDS.hxx>\n",
    "#include <TopoDS_Edge.hxx>\n",
    "#include <TopoDS_Face.hxx>\n",
    "#include <TopoDS_Wire.hxx>\n",
    "#include <TopoDS_Shape.hxx>\n",
    "#include <TopoDS_Compound.hxx>\n",
    "\n",
    "#include <TopTools_ListOfShape.hxx>\n",
    "\n",
    "TopoDS_Shape MakeBottle (const Standard_Real theWidth,\n",
    "                         const Standard_Real theHeight,\n",
    "                         const Standard_Real theThickness)\n",
    "{\n",
    "  // Profile : Define Support Points\n",
    "  gp_Pnt aPnt1(-theWidth / 2., 0, 0);\n",
    "  gp_Pnt aPnt2(-theWidth / 2., -theThickness / 4., 0);\n",
    "  gp_Pnt aPnt3(0, -theThickness / 2., 0);\n",
    "  gp_Pnt aPnt4(theWidth / 2., -theThickness / 4., 0);\n",
    "  gp_Pnt aPnt5(theWidth / 2., 0, 0);\n",
    "\n",
    "  // Profile : Define the Geometry\n",
    "  Handle(Geom_TrimmedCurve) anArcOfCircle = GC_MakeArcOfCircle(aPnt2, aPnt3, aPnt4);\n",
    "  Handle(Geom_TrimmedCurve) aSegment1 = GC_MakeSegment(aPnt1, aPnt2);\n",
    "  Handle(Geom_TrimmedCurve) aSegment2 = GC_MakeSegment(aPnt4, aPnt5);\n",
    "\n",
    "  // Profile : Define the Topology\n",
    "  TopoDS_Edge anEdge1 = BRepBuilderAPI_MakeEdge(aSegment1);\n",
    "  TopoDS_Edge anEdge2 = BRepBuilderAPI_MakeEdge(anArcOfCircle);\n",
    "  TopoDS_Edge anEdge3 = BRepBuilderAPI_MakeEdge(aSegment2);\n",
    "  TopoDS_Wire aWire = BRepBuilderAPI_MakeWire(anEdge1, anEdge2, anEdge3);\n",
    "\n",
    "  // Complete Profile\n",
    "  gp_Ax1 xAxis = gp::OX();\n",
    "  gp_Trsf aTrsf;\n",
    "\n",
    "  aTrsf.SetMirror(xAxis);\n",
    "  BRepBuilderAPI_Transform aBRepTrsf(aWire, aTrsf);\n",
    "  TopoDS_Shape aMirroredShape = aBRepTrsf.Shape();\n",
    "  TopoDS_Wire aMirroredWire = TopoDS::Wire(aMirroredShape);\n",
    "\n",
    "  BRepBuilderAPI_MakeWire mkWire;\n",
    "  mkWire.Add(aWire);\n",
    "  mkWire.Add(aMirroredWire);\n",
    "  TopoDS_Wire myWireProfile = mkWire.Wire();\n",
    "\n",
    "  // Body : Prism the Profile\n",
    "  TopoDS_Face myFaceProfile = BRepBuilderAPI_MakeFace(myWireProfile);\n",
    "  gp_Vec aPrismVec(0, 0, theHeight);\n",
    "  TopoDS_Shape myBody = BRepPrimAPI_MakePrism(myFaceProfile, aPrismVec);\n",
    "\n",
    "  // Body : Apply Fillets\n",
    "  BRepFilletAPI_MakeFillet mkFillet(myBody);\n",
    "  TopExp_Explorer anEdgeExplorer(myBody, TopAbs_EDGE);\n",
    "  while (anEdgeExplorer.More())\n",
    "  {\n",
    "    TopoDS_Edge anEdge = TopoDS::Edge(anEdgeExplorer.Current());\n",
    "    //Add edge to fillet algorithm\n",
    "    mkFillet.Add(theThickness / 12., anEdge);\n",
    "    anEdgeExplorer.Next();\n",
    "  }\n",
    "\n",
    "  myBody = mkFillet.Shape();\n",
    "\n",
    "  // Body : Add the Neck\n",
    "  gp_Pnt neckLocation(0, 0, theHeight);\n",
    "  gp_Dir neckAxis = gp::DZ();\n",
    "  gp_Ax2 neckAx2(neckLocation, neckAxis);\n",
    "\n",
    "  Standard_Real myNeckRadius = theThickness / 4.;\n",
    "  Standard_Real myNeckHeight = theHeight / 10.;\n",
    "\n",
    "  BRepPrimAPI_MakeCylinder MKCylinder(neckAx2, myNeckRadius, myNeckHeight);\n",
    "  TopoDS_Shape myNeck = MKCylinder.Shape();\n",
    "\n",
    "  myBody = BRepAlgoAPI_Fuse(myBody, myNeck);\n",
    "\n",
    "  // Body : Create a Hollowed Solid\n",
    "  TopoDS_Face   faceToRemove;\n",
    "  Standard_Real zMax = -1;\n",
    "\n",
    "  for (TopExp_Explorer aFaceExplorer(myBody, TopAbs_FACE); aFaceExplorer.More(); aFaceExplorer.Next())\n",
    "  {\n",
    "    TopoDS_Face aFace = TopoDS::Face(aFaceExplorer.Current());\n",
    "    // Check if <aFace> is the top face of the bottleâ€™s neck\n",
    "    Handle(Geom_Surface) aSurface = BRep_Tool::Surface(aFace);\n",
    "    if (aSurface->DynamicType() == STANDARD_TYPE(Geom_Plane))\n",
    "    {\n",
    "      Handle(Geom_Plane) aPlane = Handle(Geom_Plane)::DownCast(aSurface);\n",
    "      gp_Pnt aPnt = aPlane->Location();\n",
    "      Standard_Real aZ = aPnt.Z();\n",
    "      if (aZ > zMax)\n",
    "      {\n",
    "        zMax = aZ;\n",
    "        faceToRemove = aFace;\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "\n",
    "  TopTools_ListOfShape facesToRemove;\n",
    "  facesToRemove.Append(faceToRemove);\n",
    "  BRepOffsetAPI_MakeThickSolid aSolidMaker;\n",
    "  aSolidMaker.MakeThickSolidByJoin(myBody, facesToRemove, -theThickness / 50, 1.e-3);\n",
    "  myBody = aSolidMaker.Shape();\n",
    "  // Threading : Create Surfaces\n",
    "  Handle(Geom_CylindricalSurface) aCyl1 = new Geom_CylindricalSurface(neckAx2, myNeckRadius * 0.99);\n",
    "  Handle(Geom_CylindricalSurface) aCyl2 = new Geom_CylindricalSurface(neckAx2, myNeckRadius * 1.05);\n",
    "\n",
    "  // Threading : Define 2D Curves\n",
    "  gp_Pnt2d aPnt(2. * M_PI, myNeckHeight / 2.);\n",
    "  gp_Dir2d aDir(2. * M_PI, myNeckHeight / 4.);\n",
    "  gp_Ax2d anAx2d(aPnt, aDir);\n",
    "\n",
    "  Standard_Real aMajor = 2. * M_PI;\n",
    "  Standard_Real aMinor = myNeckHeight / 10;\n",
    "\n",
    "  Handle(Geom2d_Ellipse) anEllipse1 = new Geom2d_Ellipse(anAx2d, aMajor, aMinor);\n",
    "  Handle(Geom2d_Ellipse) anEllipse2 = new Geom2d_Ellipse(anAx2d, aMajor, aMinor / 4);\n",
    "  Handle(Geom2d_TrimmedCurve) anArc1 = new Geom2d_TrimmedCurve(anEllipse1, 0, M_PI);\n",
    "  Handle(Geom2d_TrimmedCurve) anArc2 = new Geom2d_TrimmedCurve(anEllipse2, 0, M_PI);\n",
    "  gp_Pnt2d anEllipsePnt1 = anEllipse1->Value(0);\n",
    "  gp_Pnt2d anEllipsePnt2 = anEllipse1->Value(M_PI);\n",
    "\n",
    "  Handle(Geom2d_TrimmedCurve) aSegment = GCE2d_MakeSegment(anEllipsePnt1, anEllipsePnt2);\n",
    "  // Threading : Build Edges and Wires\n",
    "  TopoDS_Edge anEdge1OnSurf1 = BRepBuilderAPI_MakeEdge(anArc1, aCyl1);\n",
    "  TopoDS_Edge anEdge2OnSurf1 = BRepBuilderAPI_MakeEdge(aSegment, aCyl1);\n",
    "  TopoDS_Edge anEdge1OnSurf2 = BRepBuilderAPI_MakeEdge(anArc2, aCyl2);\n",
    "  TopoDS_Edge anEdge2OnSurf2 = BRepBuilderAPI_MakeEdge(aSegment, aCyl2);\n",
    "  TopoDS_Wire threadingWire1 = BRepBuilderAPI_MakeWire(anEdge1OnSurf1, anEdge2OnSurf1);\n",
    "  TopoDS_Wire threadingWire2 = BRepBuilderAPI_MakeWire(anEdge1OnSurf2, anEdge2OnSurf2);\n",
    "  BRepLib::BuildCurves3d(threadingWire1);\n",
    "  BRepLib::BuildCurves3d(threadingWire2);\n",
    "\n",
    "  // Create Threading\n",
    "  BRepOffsetAPI_ThruSections aTool(Standard_True);\n",
    "  aTool.AddWire(threadingWire1);\n",
    "  aTool.AddWire(threadingWire2);\n",
    "  aTool.CheckCompatibility(Standard_False);\n",
    "\n",
    "  TopoDS_Shape myThreading = aTool.Shape();\n",
    "\n",
    "  // Building the Resulting Compound\n",
    "  TopoDS_Compound aRes;\n",
    "  BRep_Builder aBuilder;\n",
    "  aBuilder.MakeCompound(aRes);\n",
    "  aBuilder.Add(aRes, myBody);\n",
    "  aBuilder.Add(aRes, myThreading);\n",
    "\n",
    "  return aRes;\n",
    "}\n",
    "\n",
    "int main(int argc, char* argv[])\n",
    "{\n",
    "    TopoDS_Shape aBottle = MakeBottle(50, 70, 30);\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ahead-benefit",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%bash --out output --err error\n",
    "g++ -I/usr/local/include/opencascade/ tutorial_bottle.cpp -o tutorial_bottle /usr/local/lib/libTK*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "christian-clause",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%bash --out output --err error\n",
    "./tutorial_bottle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69e54592",
   "metadata": {},
   "outputs": [],
   "source": [
    "assert output == \"\"\n",
    "assert error == \"\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython"
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
